spring:
   application:
      name: product-service
   config:
      import: optional:configserver:http://localhost:8888

server:
   port: 0

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true