# http://localhost:8761/
spring:
  application:
    name: eureka-server

eureka:
  instance:
    appname: eureka-server
    instance-id: ${spring.application.name}:${random.uuid}
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

server:
  port: 8761
